# AuthmeGui 配置文件
# 版本: 1.0

# GUI设置
gui:
  # 是否启用GUI系统
  enabled: true
  # 玩家进入服务器时自动打开GUI
  auto-open: true
  # GUI打开延迟(tick) - 增加延迟确保AuthMe完全初始化
  open-delay: 5
  # 密码输入超时时间(秒)
  input-timeout: 50

# AuthMe集成设置
authme:
  # 是否启用AuthMe集成
  enabled: true
  # 登录成功后的操作
  login-success-actions:
    - "[message]&a登录成功！欢迎回来！"
  # 注册成功后的操作
  register-success-actions:
    - "[message]&a注册成功！欢迎加入服务器！"
  # 操作失败后的操作
  failure-actions:
    - "[message]&c操作失败，请重试！"

# 安全设置
security:
  # 最小密码长度
  min-password-length: 6
  # 最大密码长度
  max-password-length: 20
  # 密码复杂度检查
  password-complexity: false
  # 密码明文显示设置
  # true: 明文显示密码 (不安全，仅用于调试)
  # false: 隐藏密码为*号 (默认，推荐)
  show-password-plaintext: false

# 性能设置
performance:
  # GUI缓存大小
  gui-cache-size: 100
  # 配置文件重载间隔(秒)
  reload-interval: 5
